In [1]:
import sys
sys.path.append("..")

import os
import torch

base_path = "/workspace/dev/NumericalNet"
model_path = os.path.join(base_path, "outputs/20240526_test_v2", 'best_model.pth')
model = torch.load(model_path)
device = model.device
model.to(device)
unit_value_dict = model.unit_value_dict

2024-05-25 14:08:29.411667: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-25 14:08:30.118440: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


## Digit Embedding

In [2]:
value = [1, 2, 3, 10, 20, 30, 0.1, 0.2, 100, 1000, 20000]

embeddings = []
for v in value:
    v_ = torch.tensor([[v]], dtype=torch.float32).to(device)
    embeddings.append(model.get_digit_embedding(v_))

In [3]:
VALUE = 2

input_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
with torch.no_grad():
    embedding_2 = model.get_digit_embedding(input_tensor)
    embedding_2 = embedding_2.cpu()

print(embedding_2.shape)
print(embedding_2)

torch.Size([1, 512])
tensor([[ 5.5282e-01, -2.4265e-01, -9.4404e-01, -1.5783e+00, -1.4481e-01,
          1.1912e+00, -1.3148e+00, -1.1152e+00,  2.2975e-01,  5.0332e-02,
         -2.4230e-01, -4.6648e-01,  2.2242e-02,  1.5202e+00, -3.2409e-01,
         -3.4233e-01,  7.9823e-02,  6.9945e-01,  2.4941e-01, -4.9197e-02,
          2.8282e-01,  5.9812e-01,  9.3954e-02, -8.0399e-01,  8.5831e-01,
         -2.7870e-01, -1.4698e-01,  2.1053e-01, -1.0353e+00,  1.1721e+00,
         -2.2913e-01,  2.7003e-02, -2.5492e-01, -1.7402e+00, -9.8712e-01,
          6.9374e-01, -6.0973e-01, -8.3683e-01, -5.0901e-01, -1.1806e+00,
         -8.7166e-01, -1.5167e-01, -7.1305e-01,  3.4724e-01,  5.7517e-01,
          4.8580e-01, -3.2238e-01,  2.9168e+00,  3.0844e-01,  7.8124e-01,
         -4.7106e-01,  5.9043e-01,  1.1760e-01,  4.1823e-01,  6.4495e-02,
         -8.3066e-01,  4.8130e-01, -8.2000e-01,  8.5651e-01, -6.7899e-01,
          4.4757e-02,  1.4789e+00, -1.5097e+00, -2.4518e-01,  5.0254e-01,
         -1.1052e

In [4]:
VALUE = 1

input_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
with torch.no_grad():
    embedding_1 = model.get_digit_embedding(input_tensor)
    embedding_1 = embedding_1.cpu()

print(embedding_1.shape)
print(embedding_1)

torch.Size([1, 512])
tensor([[ 5.4190e-01, -2.3656e-01, -9.3657e-01, -1.5769e+00, -1.4936e-01,
          1.1667e+00, -1.3073e+00, -1.1155e+00,  2.0726e-01,  5.4328e-02,
         -2.5609e-01, -4.5721e-01,  2.1010e-02,  1.5210e+00, -3.1918e-01,
         -3.4882e-01,  9.2289e-02,  6.8338e-01,  2.4791e-01, -6.0098e-02,
          2.7781e-01,  6.0029e-01,  7.8757e-02, -7.9404e-01,  8.5208e-01,
         -2.9411e-01, -1.6669e-01,  1.9483e-01, -1.0396e+00,  1.1692e+00,
         -2.2806e-01,  2.8258e-02, -2.4443e-01, -1.7494e+00, -9.8941e-01,
          6.8136e-01, -6.2132e-01, -8.1177e-01, -4.9660e-01, -1.1836e+00,
         -8.9047e-01, -1.5742e-01, -7.1705e-01,  3.4601e-01,  5.6114e-01,
          4.6348e-01, -3.2466e-01,  2.9060e+00,  3.0428e-01,  7.9586e-01,
         -4.5960e-01,  5.6595e-01,  1.0924e-01,  4.2659e-01,  6.8935e-02,
         -8.1837e-01,  4.8371e-01, -8.1371e-01,  8.7473e-01, -6.5710e-01,
          4.2336e-02,  1.4666e+00, -1.4861e+00, -2.6577e-01,  5.0335e-01,
         -1.0924e

In [5]:
VALUE = 3

input_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
with torch.no_grad():
    embedding_3 = model.get_digit_embedding(input_tensor)
    embedding_3 = embedding_3.cpu()

print(embedding_3.shape)
print(embedding_3)

torch.Size([1, 512])
tensor([[ 5.6046e-01, -2.4695e-01, -9.4873e-01, -1.5781e+00, -1.4143e-01,
          1.2081e+00, -1.3193e+00, -1.1143e+00,  2.4605e-01,  4.7520e-02,
         -2.3206e-01, -4.7276e-01,  2.3107e-02,  1.5186e+00, -3.2755e-01,
         -3.3750e-01,  7.0977e-02,  7.1028e-01,  2.5048e-01, -4.0999e-02,
          2.8631e-01,  5.9603e-01,  1.0497e-01, -8.1088e-01,  8.6214e-01,
         -2.6748e-01, -1.3243e-01,  2.2217e-01, -1.0312e+00,  1.1733e+00,
         -2.2956e-01,  2.5945e-02, -2.6234e-01, -1.7323e+00, -9.8484e-01,
          7.0253e-01, -6.0071e-01, -8.5419e-01, -5.1754e-01, -1.1776e+00,
         -8.5708e-01, -1.4753e-01, -7.0971e-01,  3.4779e-01,  5.8488e-01,
          5.0152e-01, -3.2071e-01,  2.9224e+00,  3.1124e-01,  7.6994e-01,
         -4.7893e-01,  6.0775e-01,  1.2356e-01,  4.1183e-01,  6.1178e-02,
         -8.3892e-01,  4.7912e-01, -8.2415e-01,  8.4249e-01, -6.9445e-01,
          4.6525e-02,  1.4870e+00, -1.5255e+00, -2.2978e-01,  5.0123e-01,
         -1.1138e

In [6]:
VALUE=1.9
input_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
with torch.no_grad():
    embedding_1_9 = model.get_digit_embedding(input_tensor)
    embedding_1_9 = embedding_1_9.cpu()
    
print(embedding_1_9.shape)
print(embedding_1_9)

torch.Size([1, 512])
tensor([[ 5.5190e-01, -2.4213e-01, -9.4345e-01, -1.5782e+00, -1.4521e-01,
          1.1892e+00, -1.3142e+00, -1.1152e+00,  2.2783e-01,  5.0669e-02,
         -2.4349e-01, -4.6571e-01,  2.2138e-02,  1.5203e+00, -3.2367e-01,
         -3.4289e-01,  8.0878e-02,  6.9813e-01,  2.4928e-01, -5.0146e-02,
          2.8240e-01,  5.9833e-01,  9.2656e-02, -8.0316e-01,  8.5782e-01,
         -2.8002e-01, -1.4868e-01,  2.0918e-01, -1.0357e+00,  1.1719e+00,
         -2.2906e-01,  2.7120e-02, -2.5403e-01, -1.7411e+00, -9.8735e-01,
          6.9270e-01, -6.1076e-01, -8.3474e-01, -5.0797e-01, -1.1809e+00,
         -8.7333e-01, -1.5216e-01, -7.1342e-01,  3.4715e-01,  5.7400e-01,
          4.8392e-01, -3.2258e-01,  2.9161e+00,  3.0809e-01,  7.8253e-01,
         -4.7011e-01,  5.8836e-01,  1.1689e-01,  4.1897e-01,  6.4880e-02,
         -8.2965e-01,  4.8153e-01, -8.1948e-01,  8.5812e-01, -6.7714e-01,
          4.4550e-02,  1.4779e+00, -1.5078e+00, -2.4697e-01,  5.0265e-01,
         -1.1042e

In [7]:
VALUE = 2.6
input_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
with torch.no_grad():
    embedding_2_6 = model.get_digit_embedding(input_tensor)
    embedding_2_6 = embedding_2_6.cpu()
    
print(embedding_2_6.shape)
print(embedding_2_6)

torch.Size([1, 512])
tensor([[ 5.5769e-01, -2.4539e-01, -9.4709e-01, -1.5783e+00, -1.4267e-01,
          1.2020e+00, -1.3178e+00, -1.1147e+00,  2.4010e-01,  4.8535e-02,
         -2.3582e-01, -4.7052e-01,  2.2794e-02,  1.5193e+00, -3.2629e-01,
         -3.3927e-01,  7.4182e-02,  7.0642e-01,  2.5009e-01, -4.4022e-02,
          2.8505e-01,  5.9684e-01,  1.0095e-01, -8.0839e-01,  8.6081e-01,
         -2.7157e-01, -1.3777e-01,  2.1789e-01, -1.0328e+00,  1.1730e+00,
         -2.2944e-01,  2.6346e-02, -2.5965e-01, -1.7353e+00, -9.8573e-01,
          6.9934e-01, -6.0407e-01, -8.4794e-01, -5.1447e-01, -1.1788e+00,
         -8.6249e-01, -1.4904e-01, -7.1097e-01,  3.4763e-01,  5.8138e-01,
          4.9583e-01, -3.2132e-01,  2.9206e+00,  3.1024e-01,  7.7413e-01,
         -4.7610e-01,  6.0147e-01,  1.2139e-01,  4.1420e-01,  6.2401e-02,
         -8.3597e-01,  4.7995e-01, -8.2267e-01,  8.4769e-01, -6.8885e-01,
          4.5878e-02,  1.4842e+00, -1.5199e+00, -2.3545e-01,  5.0179e-01,
         -1.1107e

In [8]:
# norm_value1 vs norm_value2 vs norm_value3

norm_value1 = torch.norm(embedding_1, p=2, dim=1)
norm_value1_9 = torch.norm(embedding_1_9, p=2, dim=1)
norm_value2 = torch.norm(embedding_2, p=2, dim=1)
norm_value2_6 = torch.norm(embedding_2_6, p=2, dim=1)
norm_value3 = torch.norm(embedding_3, p=2, dim=1)

print(f"norm_value1: {norm_value1}")
print(f"norm_value1_9: {norm_value1_9}")
print(f"norm_value2: {norm_value2}")
print(f"norm_value2_6: {norm_value2_6}")
print(f"norm_value3: {norm_value3}")

norm_value1: tensor([18.3588])
norm_value1_9: tensor([18.4472])
norm_value2: tensor([18.4546])
norm_value2_6: tensor([18.4926])
norm_value3: tensor([18.5127])


In [9]:
VALUE, UNIT = 2, "m"
input_value_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
intput_unit_tensor = torch.tensor([[unit_value_dict[UNIT]]], dtype=torch.float32).to(device)

with torch.no_grad():
    embedding_2_m = model.get_joint_embedding(input_value_tensor, intput_unit_tensor)
    embedding_2_m = embedding_2_m.cpu()
    
print(embedding_2_m.shape)

torch.Size([1, 512])


In [10]:
VALUE, UNIT = 2.1, "m"
input_value_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
intput_unit_tensor = torch.tensor([[unit_value_dict[UNIT]]], dtype=torch.float).to(device)

with torch.no_grad():
    embedding_2_1_m = model.get_joint_embedding(input_value_tensor, intput_unit_tensor)
    embedding_2_1_m = embedding_2_1_m.cpu()
    
print(embedding_2_1_m.shape)

torch.Size([1, 512])


In [11]:
VALUE, UNIT = 0.5, "m"
input_value_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
intput_unit_tensor = torch.tensor([[unit_value_dict[UNIT]]], dtype=torch.float).to(device)

with torch.no_grad():
    embedding_0_5_m = model.get_joint_embedding(input_value_tensor, intput_unit_tensor)
    embedding_0_5_m = embedding_0_5_m.cpu()
    
print(embedding_0_5_m.shape)

torch.Size([1, 512])


In [12]:
VALUE, UNIT = 80, "m"
input_value_tensor = torch.tensor([[VALUE]], dtype=torch.float32).to(device)
intput_unit_tensor = torch.tensor([[unit_value_dict[UNIT]]], dtype=torch.float).to(device)

with torch.no_grad():
    embedding_80_m = model.get_joint_embedding(input_value_tensor, intput_unit_tensor)
    embedding_80_m = embedding_80_m.cpu()
    
print(embedding_80_m.shape)

torch.Size([1, 512])


In [13]:
norm_2_m = torch.norm(embedding_2_m, p=2, dim=1)
norm_2_1_m = torch.norm(embedding_2_1_m, p=2, dim=1)
norm_0_5_m = torch.norm(embedding_0_5_m, p=2, dim=1)
norm_80_m = torch.norm(embedding_80_m, p=2, dim=1)

print(f"norm_0_5_m: {norm_0_5_m.item()}")
print(f"norm_2_m: {norm_2_m.item()}")
print(f"norm_2_1_m: {norm_2_1_m.item()}")
print(f"norm_80_m: {norm_80_m.item()}")

norm_0_5_m: 14.256962776184082
norm_2_m: 14.256956100463867
norm_2_1_m: 14.256954193115234
norm_80_m: 14.2569580078125


In [14]:
units = ['cm', 'm', 'km', 'l', 'ml', 'kg', 'mg', 'g']
unit_embeddings = []
for u in units:
    u_ = torch.tensor([[unit_value_dict[u]]], dtype=torch.float32).to(device)
    with torch.no_grad():
        unit_embeddings.append(model.get_unit_embedding(u_).to('cpu'))
    
print(unit_embeddings[0].shape)

torch.Size([1, 512])


In [15]:
for i, u in enumerate(units):
    print(f"unit: {u}:")
    print(unit_embeddings[i][0][:10])
    print()

unit: cm:
tensor([-0.0356, -0.4870, -0.5910, -0.3896, -0.3751, -0.6683,  0.7007,  1.5459,
        -1.1943, -0.2805])

unit: m:
tensor([-0.0350, -0.4849, -0.5746, -0.3972, -0.3824, -0.6565,  0.6836,  1.5319,
        -1.1720, -0.2892])

unit: km:
tensor([-0.0360, -0.4886, -0.6079, -0.3812, -0.3670, -0.6804,  0.7182,  1.5592,
        -1.2169, -0.2710])

unit: l:
tensor([-0.0368, -0.4905, -0.6429, -0.3619, -0.3478, -0.7051,  0.7545,  1.5833,
        -1.2624, -0.2491])

unit: ml:
tensor([-0.0370, -0.4904, -0.6608, -0.3509, -0.3366, -0.7176,  0.7729,  1.5934,
        -1.2848, -0.2365])

unit: kg:
tensor([-0.0370, -0.4894, -0.6786, -0.3389, -0.3240, -0.7300,  0.7914,  1.6017,
        -1.3066, -0.2227])

unit: mg:
tensor([-0.0366, -0.4843, -0.7135, -0.3116, -0.2947, -0.7538,  0.8276,  1.6108,
        -1.3471, -0.1913])

unit: g:
tensor([-0.0369, -0.4874, -0.6963, -0.3258, -0.3101, -0.7421,  0.8097,  1.6076,
        -1.3275, -0.2077])

